import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Intercolegiales',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <img src="/head_intercolegiales.webp" />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
